version: '3'
services: 
  db:
    image: mysql:latest
    restart: always
    env_file: ./.env
    ports:
      - $SLACK_CC_MYSQL_LOCAL_PORT:$SLACK_CC_MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: "eberhm/slack_gh_code_challenge_app:latest"
    ports:
      - $SLACK_CC_APP_LOCAL_PORT:$SLACK_CC_APP_DOCKER_PORT
    env_file:
      - ./.env
    volumes: 
      - ./:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
volumes: 
  db-config:
  db-data:
